name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
#    if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.0.3
        with:
          PROJECT_FILE_PATH: Fallible/Fallible.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
